<?php

namespace UserBundle\Controller;

use FOS\UserBundle\Controller\RegistrationController as BaseController;
use FOS\UserBundle\Model\UserInterface;
use Symfony\Component\HttpFoundation\Response;

class RegistrationController extends BaseController
{
    protected function authenticateUser(UserInterface $user, Response $response)
    {
        parent::authenticateUser($user, $response); // TODO: Change the autogenerated stub
    }

}
